### PR TITLE
feat: :rocket: Add button `background-animation-button`

### PR DESCRIPTION
**Pull request by guptasajal411**
## What is the change?
Added background-animation-button

## Related issue?
closes: #25 

## How was it tested?
Open `index.html` with Live Server
## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [X] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [X] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [X] Have you made corresponding changes to the documentation?
-   [X] Have you tested the code before submission?
-   [X] Have you formatted your code ? (You can use any html,css beautifier)
-   [X] My changes generates no new warnings.
-   [X] I'm Hacktoberfest'21 contributor.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by siddhi-244** [comment]
Create new issue for this button and try to add more effects to it !

**Comment by guptasajal411** [comment]
I have also added more pseudoclasses like `active` & `focus`, do you have any more ideas for the animation?

**Comment by siddhi-244** [comment]
> Issue #25 created! I have also added more pseudoclasses like `active` & `focus`, do you have any more ideas for the animation?

Ok sure

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Remove ripple loader gif .

**Comment by guptasajal411** [comment]
> Remove ripple loader gif .

My bad 😅 Fixed now!

**Review by siddhi-244 — APPROVED** [review]
Add your topic in general readme here https://github.com/siddhi-244/Embellish/tree/main/HTML%2BCSS%2BJS

**Review by siddhi-244 — APPROVED** [review]

**Comment by siddhi-244** [comment]
Great work @guptasajal411 . Keep contributing 🎊🎊🎊

**Pull request merged**
