### PR TITLE
Added Hero Sections

### PR DESCRIPTION
**Pull request by thevipinmishra**
# What is the change?
Remove this line and add a description

## Related issue?
closes: #issue_number

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

Issue - #19

### CODE REVIEW

**Comment by siddhi-244** [comment]
Link issue

**Comment by thevipinmishra** [comment]
Sorry, just linked the issue.

**Comment by siddhi-244** [comment]
Why you added 2 hero sections in 1 pr. Make separate prs for separate things

**Comment by thevipinmishra** [comment]
Leaving it here as it is, I though I was making a contribution but I don't know where this particular rule came from. Thanks!

**Comment by siddhi-244** [comment]
> Leaving it here as it is, I though I was making a contribution but I don't know where this particular rule came from. Thanks!

I think I was helping you getting 2 prs but you don't want it! Good

**Pull request closed without merging**
