### PR TITLE
Added animated-search-bar in Search Bar directory

### PR DESCRIPTION
**Pull request by arkayyy**
## What is the change?
Added the animated-search-bar folder with index.html,index.css and README.md, inside the Search Bar directory. This component is an animated search bar using only HTML and CSS, which can be implemented in any project of choice. 

## Related issue?
closes: #44 

## How was it tested?
The code has been tested with Live Preview in VS Code and chrome and firefox web browsers.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created
Screen-Recording-_02-10-2021-13-53-28_
:

### CODE REVIEW

**Comment by arkayyy** [comment]
@siddhi-244 I have added my component in the main README.md file also. Kindly accept my pull request. Thank you.

**Comment by siddhi-244** [comment]
Add only 1 component per pr.

**Comment by arkayyy** [comment]
@siddhi-244 I have made 2 separate PRs. One is #63 for the 'animated search bar' component, and #56 for the 'glowing animated button' component. I have added only 1 component per PR. Please do check it. Thanks.

**Comment by siddhi-244** [comment]
> @siddhi-244 I have made 2 separate PRs. One is #63 for the 'animated search bar' component, and #56 for the 'glowing animated button' component. I have added only 1 component per PR. Please do check it. Thanks.

But you have made it from same branch. The files are there in both the pra

**Comment by arkayyy** [comment]
@siddhi-244 Sorry for the inconvenience caused, as I told it was my first time, I didn't know at first about changing the branch for every component. So by mistake I pushed both components (animated glowing button and animated search bar) from same branch (apkbranch). But after that, I successfully removed one component files from earlier branch, and created a new branch  apk1branch, and pushed the animated search bar component from the new branch. Do I need to make any other changes?

**Pull request closed without merging**
