### PR TITLE
Testimonial section

### PR DESCRIPTION
**Pull request by khushimarothi**
## What is the change?
Created Testimonials section as a component.

## Related issue?
closes: #282 

## How was it tested?
Tested on my Laptop.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
There is no readme. Also no data added in componentData.json file. All these guidelines are there in the main readme. Don't make a separate folder for css all should be in same folder just images should have a different folder

**Comment by khushimarothi** [comment]
Okay. Can I add the ss instead of the video? Cause I'm facing some issues in my laptop so installing up the screen recorder will not be feasible.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You can add pictures too. But there is no readme right now !

**Comment by khushimarothi** [comment]
> You can add pictures too. But there is no readme right now !

I was waiting for your reply.  Will update it too

**Comment by khushimarothi** [comment]
I have updated readme for my work too.

**Comment by khushimarothi** [comment]
@siddhi-244  please check.

**Comment by siddhi-244** [comment]
Cool

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Pull request merged**
