### PR TITLE
Animated-Background

### PR DESCRIPTION
**Pull request by shreyamedehal**
## What is the change?
added animated background

## Related issue?
closes: #26

## How was it tested?
live server

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:

https://user-images.githubusercontent.com/82696347/135619576-47bd180d-26f6-4a14-b470-bef0cc69b86b.mp4

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Don't add space in folder name add hyphen(-)

**Comment by siddhi-244** [comment]
Also add ur component name to general readme

**Comment by siddhi-244** [comment]
> Also add ur component name to general readme

Here : https://github.com/siddhi-244/Embellish/tree/main/HTML%2BCSS%2BJS

**Comment by siddhi-244** [comment]
> > Also add ur component name to general readme
> 
> Here : https://github.com/siddhi-244/Embellish/tree/main/HTML%2BCSS%2BJS

Plzz see to it.

**Comment by shreyamedehal** [comment]
Done!

**Comment by siddhi-244** [comment]
> Also add ur component name to general readme

Do this!

**Comment by shreyamedehal** [comment]
yes done, i opened a new pr for that

**Comment by siddhi-244** [comment]
> yes done, i opened a new pr for that

You can't do that

**Review by siddhi-244 — APPROVED** [review]
Great work🎊🎊

**Pull request merged**
