### PR TITLE
added glowing icons with hover

### PR DESCRIPTION
**Pull request by srinjoy-26**
## What is the change?
added glowing icons with hover effect.

## Related issue?
closes: #260 

## How was it tested?
I hv tested it on my local system.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

hosted link - https://srinjoy-26.github.io/Glowing-icons-with-amazing-css-effect/#

### CODE REVIEW

**Comment by srinjoy-26** [comment]
please review now @siddhi-244

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Don't add links in demo. Add a gif or video of the component

**Comment by siddhi-244** [comment]
Why have you checked every box in pr template? I see you haven't commented your code but still checked it. Please see to this !

**Comment by srinjoy-26** [comment]
> Why have you checked every box in pr template? I see you haven't commented your code but still checked it. Please see to this !

OK unchecked it

**Comment by siddhi-244** [comment]
Remove that link from demo and add a video of your component.  Also add your component in the general readme.

**Comment by srinjoy-26** [comment]
> Remove that link from demo and add a video of your component. Also add your component in the general readme.

where is the general readme and what do I need to add there please explain @siddhi-244

**Comment by siddhi-244** [comment]
> > Remove that link from demo and add a video of your component. Also add your component in the general readme.
> 
> where is the general readme and what do I need to add there please explain @siddhi-244

It's a readme that contains list of components.  Just open the folders and check

**Pull request closed without merging**
