### PR TITLE
Footer design updated

### PR DESCRIPTION
**Pull request by AB-Jeet**
## What is the change?
updated my old footer design

## Related issue?
issue related to #80

## How was it tested?
tested on VS code and Google Crome

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x ] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [ x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [ x] Have you made corresponding changes to the documentation?
-   [x ] Have you tested the code before submission?
-   [ x Have you formatted your code ? (You can use any html,css beautifier)
-   [x ] My changes generates no new warnings.
-   [x ] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.
Here the tested ss
footer small screen
footer full screen mode
 

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by AB-Jeet** [comment]
Pls consider my updated footer design PR #114  for the issue #80

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Follow the folder structure add a readme and demo

**Comment by AB-Jeet** [comment]
@siddhi-244  completed the changes pls consider the updated PR for the issue #80

**Comment by siddhi-244** [comment]
> @siddhi-244 completed the changes pls consider the updated PR for the issue #80 . Branch has one conflict how can I resolve it ?? Pls guide.

Resolve conflicts

**Pull request closed without merging**
