### PR TITLE
Glassmorphism Card Added

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
## What is the change?
A simple Glassmorphism card created with HTML and CSS.

## Related issue?
closes: #271 

## How was it tested?
In vscode

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code? (You can use any HTML, CSS beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.

## GIF/video of the working component you created:
Add here the GIF you created.

https://user-images.githubusercontent.com/73753957/180608863-2f5aeeb1-7178-4927-9f54-aaeadce118a6.mp4

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Hey, it would be great if you can add the card to the middle of the page. It would look awesome ! Also add your component in json file and general readme and the folder name should not have spaces. It should have _ or -

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Card added in both files and changed the position to center

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add demo video or gif in readme

**Comment by gurjeetsinghvirdee** [comment]
> Add demo video or gif in readme

Done

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You said you have made the card in middle but the demo shows it on top !

**Comment by gurjeetsinghvirdee** [comment]
> You said you have made the card in middle but the demo shows it on top !

updated video

**Review by siddhi-244 — APPROVED** [review]
LGTM🥳🥳

**Pull request merged**
