### PR TITLE
Added style to the scroll bar

### PR DESCRIPTION
**Pull request by niladrix719**
## What is the change?
Added some styling to the scroll bar

## Related issue?
closes: #317 

## How was it tested?
it's tested in my local machine

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [ ] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

s

### CODE REVIEW

**Comment by siddhi-244** [comment]
Unable to play the video ! Plzz re-upload it !

**Comment by niladrix719** [comment]
> Unable to play the video ! Plzz re-upload it !

done

**Comment by siddhi-244** [comment]
> > Unable to play the video ! Plzz re-upload it !
> 
> done

Still unable to play it. Add screenshots !

**Comment by niladrix719** [comment]
> > > Unable to play the video ! Plzz re-upload it !
> > 
> > 
> > done
> 
> Still unable to play it. Add screenshots !

done

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
