### PR TITLE
Dynamic_Progress_Bar

### PR DESCRIPTION
**Pull request by SurajPratap10**
## What is the change?
I have added a new progress bar component

## Related issue?
closes:  #334 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

https://user-images.githubusercontent.com/92919173/216299535-5e7195fd-32a9-408e-9f16-e36d77832805.mp4

### CODE REVIEW

**Comment by SurajPratap10** [comment]
I tried to remove commits via terminal (soft) but it seems there is some issue with that as I tried many times but commits didn't revert, So if you merge this PR (it is fully correct and according to code of conduct) all the previous commits will automatically disappear and from next time I would be able to PR with fresh commits

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add your component name in readme inside html+css+js folder !

**Comment by SurajPratap10** [comment]
> Add your component name in readme inside html+css+js folder !

Ok, so from now on we have to add on readme and json? as earlier you told us to only mention it in the JSON file.

**Comment by SurajPratap10** [comment]
> > Add your component name in readme inside html+css+js folder !
> 
> Ok, so from now on we have to add on readme and json? as earlier you told us to only mention it in the JSON file.

added to the README

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
