### PR TITLE
added Category Section

### PR DESCRIPTION
**Pull request by niladrix719**
## What is the change?
1. A Category section for the Components is added to the page, by clicking on a particular category the user gets navigated to a page that has components of that category only.

2. The Get Started button now navigates the user to the Category section rather than the features section.

3. The 3 random components at the bottom of the page are now below the heading random suggestions.

4. added some objects in json file which were previously missing.

5. added some top margins to the footer when the content is less than the window height on the components page
## Related issue?
closes: #348

## How was it tested?
Tested in Deploy Preview

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [ ] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

[screen-recording (5).webm](https://user-images.githubusercontent.com/91966855/216830222-1addbcfd-0d70-465d-a71c-b32729fde811.webm)

### CODE REVIEW

**Comment by siddhi-244** [comment]
There are some files that are renamed ! Cab you explain why is it so ?

**Comment by niladrix719** [comment]
> There are some files that are renamed ! Cab you explain why is it so ?

yeah I have added '-' between them (i.e. from Mouse Hover to Mouse-Hover), this was done because I am fetching the component names as strings and comparing them with id of the components. And Since Id cannot have spaces between them so I had to rename the file names, so the checking could take place (i.e category name == category id), the checking is done so that I can only place the components with same category on the page

**Review by siddhi-244 — COMMENTED** [review]
Can you change the path in componentData.json too?

**Comment by niladrix719** [comment]
> Can you change the path in componentData.json too?

yeah paths are already changed in json file

**Review by siddhi-244 — APPROVED** [review]

**Comment by niladrix719** [comment]
> Can you change the path in componentData.json too?

ok I think I missed some , let me change them

**Comment by siddhi-244** [comment]
Awesome work !

**Pull request merged**
