### PR TITLE
changed content in the contact page

### PR DESCRIPTION
**Pull request by afreenabegum**
@siddhi-244 ,Once please review my changes.

### CODE REVIEW

**Comment by afreenabegum** [comment]
@siddhi-244 , I made some changes, kindly, please review that.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Instead of call us you can write Github and use github icon

**Comment by afreenabegum** [comment]
> Instead of call us you can write Github and use github icon

Am not getting where to place github icon in the source code. Could you please  tell me where to place Github icon.

**Comment by siddhi-244** [comment]
> > Instead of call us you can write Github and use github icon
> 
> Am not getting where to place github icon in the source code. Could you please tell me where to place Github icon. @siddhi-244

Hey, the codebase is really easy to understand.  You need to figure it out !

**Comment by afreenabegum** [comment]
> > > Instead of call us you can write Github and use github icon
> > 
> > 
> > Am not getting where to place github icon in the source code. Could you please tell me where to place Github icon. @siddhi-244
> 
> Hey, the codebase is really easy to understand. You need to figure it out !

No mam, Actually I thought of changing icons since long when I commented on issue itself ,but am not find till now. I found that icons are not in links or images but written in some name format? At least try to provide me any hint. I'll figure it out.

**Comment by siddhi-244** [comment]
> > > > Instead of call us you can write Github and use github icon
> > > 
> > > 
> > > Am not getting where to place github icon in the source code. Could you please tell me where to place Github icon. @siddhi-244
> > 
> > 
> > Hey, the codebase is really easy to understand. You need to figure it out !
> 
> No mam, Actually I thought of changing icons since long when I commented on issue itself ,but not found till now. I found that icons are not in links or images but written in some name format? At least try to provide me any hint. I'll figure it out.

It's taken from a third party. Look at the i tag. Check the links in head tag. There you will get it.

**Comment by siddhi-244** [comment]
It's not placed properly

**Comment by siddhi-244** [comment]
Nope. It still isn't placed. Do one thing just go back to the previous version where it had that phone call icon

**Comment by siddhi-244** [comment]
Still the icon is not placed properly

**Comment by siddhi-244** [comment]
Give it proper class names

**Comment by siddhi-244** [comment]
Closing this pr as it's been more than 7 days.

**Pull request closed without merging**
