### PR TITLE
adding instruction about adding json file in readme.md file

### PR DESCRIPTION
**Pull request by afreenabegum**
Added how to add component in JSON file in instructions in readme.md file.

@siddhi-244 Kindly please check the PR.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Check the json file present in this repository and the format of that example should be the same as in this repo.

**Comment by afreenabegum** [comment]
> Check the json file present in this repository and the format of that example should be the same as in this repo.

Should I write example mentioned in labels.json?

**Comment by siddhi-244** [comment]
> > Check the json file present in this repository and the format of that example should be the same as in this repo.
> 
> Should I write example mentioned in labels.json?

Check the folder Embellish website. That json file

**Comment by afreenabegum** [comment]
Should I add Example from  componentData.json?

**Comment by siddhi-244** [comment]
> Should I add Example from componentData.json?

Yes!

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You literally added the whole json file here. Aren't my explanations clear to you? You can tag me on discord and we can have a short voice call.

**Comment by afreenabegum** [comment]
> You literally added the whole json file here. Aren't my explanations clear to you? You can tag me on discord and we can have a short voice call.

am not getting which example should I add.

**Comment by siddhi-244** [comment]
LGTM ! 🥳🥳

**Review by siddhi-244 — APPROVED** [review]

**Comment by afreenabegum** [comment]
Thank you @siddhi-244 for guiding : )

**Pull request merged**
