### PR TITLE
Add Gradient-Background

### PR DESCRIPTION
**Pull request by Danix421**
## What is the change?
Add Gradient Background on Background components.

## Related issue?
No.

## How was it tested?
It's pure HTML and CSS, so just opening the `index.html` on a browser.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by siddhi-244** [comment]
Create a issue first

**Comment by Danix421** [comment]
@siddhi-244 #104.

**Comment by siddhi-244** [comment]
We need a designed one this is so simple

**Comment by Danix421** [comment]
> We need a designed one this is so simple

More colors? What do you mean?

**Pull request closed without merging**
