### PR TITLE
Added shuffle text animation #27

### PR DESCRIPTION
**Pull request by Nikhita28**
## What is the change?
I added the shuffle text animation here.
## Related issue?
closes: #27 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x ] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [ x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [ ] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x ] I'm Hacktoberfest'21 contributor.

## GIF/video of the working of component you created:
Add here the GIF you created.
Screen Recording (01-10-2021 05-56-06 PM)

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add a readme. Follow the previous merged prs.

**Comment by siddhi-244** [comment]
And don't give spaces in folder name. Give a hyphen

**Comment by siddhi-244** [comment]
Are you done? Shall I review it?

**Comment by Nikhita28** [comment]
Yes I am done. Actually I saw the second comment later so I made another commit for that.

**Comment by siddhi-244** [comment]
Add ur component name to general readme : here 
https://github.com/siddhi-244/Embellish/tree/main/HTML%2BCSS%2BJS

**Comment by siddhi-244** [comment]
Let me know once you are done

**Review by siddhi-244 — APPROVED** [review]
Great work🎊🎊🎊

**Pull request merged**
