### PR TITLE
Added glowing-animated-button in buttons folder

### PR DESCRIPTION
**Pull request by arkayyy**
## What is the change?
Added Glowing Animated Button files in glowing-animated-button folder in buttons directory. The files included are: index.html, index.css and readme.md .

## Related issue?
closes: #46

## How was it tested?
The code was tested using Live Preview in VSCode and also with Chrome and Firefox web browsers and was found to be working perfectly fine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Screen-Recording-_02-10-2021-13-02-00_

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add your component name in general readme

**Comment by arkayyy** [comment]
@siddhi-244 I have added my component in the general readme as told. Kindly approve the pull request. Thank you.

**Comment by siddhi-244** [comment]
> @siddhi-244 I have added my component in the general readme as told. Kindly approve the pull request. Thank you.

You have added button also.

**Comment by arkayyy** [comment]
@siddhi-244 I have added my first component 'animated glowing button' for PR #56  from apkbranch, and 'animated search bar' for PR #63 
 from apk1branch.

**Pull request closed without merging**
