### PR TITLE
Toggle Button added

### PR DESCRIPTION
**Pull request by yashkondewar**
## What is the change?
Added toggle button.

## Related issue?
closes: #292 

## How was it tested?
Tested on VS code.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:

https://user-images.githubusercontent.com/98695632/182649670-9c9d6d54-12ca-4947-af3c-d81cc0f366dc.mp4

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add your component to general readme

**Comment by yashkondewar** [comment]
> Add your component to the general readme

Already added mam

**Comment by siddhi-244** [comment]
No you havent

**Comment by yashkondewar** [comment]
> No you havent

But it's visible from my side.

**Comment by siddhi-244** [comment]
You haven't committed it ig

**Comment by yashkondewar** [comment]
> You haven't committed it ig

Done

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Pull request merged**
