### PR TITLE
responsiveness

### PR DESCRIPTION
**Pull request by aswinikalyan30**
## What is the change?
Modified a few elements to enhance responsiveness

## Related issue?
closes: #227 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [ ] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm OpenCode contributor.
-   [ ] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by siddhi-244** [comment]
> ## What is the change?
> Modified a few elements to enhance responsiveness
> 
> ## Related issue?
> closes: #227
> 
> ## How was it tested?
> Remove this line and tell us how the code was tested.
> 
> ## Checklist:
> Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:
> 
> * [x]  Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
> * [x]  Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
> * [ ]  Have you made corresponding changes to the documentation?
> * [x]  Have you tested the code before submission?
> * [x]  Have you formatted your code ? (You can use any html,css beautifier)
> * [x]  My changes generates no new warnings.
> * [x]  I'm OpenCode contributor.
> * [ ]  I have commented my code, particularly in hard-to-understand areas.
> 
> ## GIF/video of the working of component you created:
> Add here the GIF you created.

Add the screenshots of the output !

**Comment by aswinikalyan30** [comment]
Hnet-image (1)

**Comment by aswinikalyan30** [comment]
Yeah sure

**Comment by aswinikalyan30** [comment]
image


done!

**Comment by siddhi-244** [comment]
> image
> 
> done!

Is it responsive? And add it at the end just above the footer 🙂

**Comment by aswinikalyan30** [comment]
> > image
> > done!
> 
> Is it responsive? And add it at the end just above the footer

Yes it is responsive, okay ill do that

**Comment by aswinikalyan30** [comment]
hey, if you add it at the footer, it wont be that visible to people on the site, also logically, this must come before seeing all the other components, if you still want it anyway, ill do it

**Comment by siddhi-244** [comment]
> hey, if you add it at the footer, it wont be that visible to people on the site, also logically(and from design perspective), this must come before seeing all the other components, if you still want it anyway, ill do it

Don't add it at the footer ! You have to add it above the footer ! After the components !

**Comment by aswinikalyan30** [comment]
> > hey, if you add it at the footer, it wont be that visible to people on the site, also logically(and from design perspective), this must come before seeing all the other components, if you still want it anyway, ill do it
> 
> Don't add it at the footer ! You have to add it above the footer ! After the components !

yes, if you add above the footer, its getting kinda merged with the footer, since its the same bg, which is why i thought it will be better if you put it above the components

**Comment by siddhi-244** [comment]
> > > hey, if you add it at the footer, it wont be that visible to people on the site, also logically(and from design perspective), this must come before seeing all the other components, if you still want it anyway, ill do it
> > 
> > 
> > Don't add it at the footer ! You have to add it above the footer ! After the components !
> 
> yes, if you add above the footer, its getting kinda merged with the footer, since its the same bg, which is why i thought it will be better if you put it above the components

Cool ! I will merge it ! Thank you for contributing.  I will add a level 2 label for your great work !

**Comment by aswinikalyan30** [comment]
Thanks :))

**Pull request merged**
