### PR TITLE
Add a hover effect on navigation links

### PR DESCRIPTION
**Pull request by muditchoudhary**
## What is the change?
Add a hover effect on navigation links

## Related issue?
closes: #283

## How was it tested?
Tested on chrome browser.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [ ] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [ ] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm HSOC22 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.
Peek 2022-08-02 17-37

### CODE REVIEW

**Comment by siddhi-244** [comment]
What if you keep only the downward dash and not the upward one ?

**Comment by muditchoudhary** [comment]
> What if you keep only the downward dash and not the upward one ?

Alright, it would be good too

**Comment by muditchoudhary** [comment]
hey, @siddhi-244 Made the change.

**Review by siddhi-244 — APPROVED** [review]
Looks awesome

**Pull request merged**
