### PR TITLE
Animated Profile Card

### PR DESCRIPTION
**Pull request by TechSpiritSS**
## What is the change?
It adds an animated profile card template in card section

## Related issue?
closes: #115 

## How was it tested?
The code was tested by using live server extension in VSCode

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
FeUsH3LVTS

### CODE REVIEW

**Comment by siddhi-244** [comment]
Add a hyphen in name of folder !

**Comment by siddhi-244** [comment]
Add your component to general readme.

**Comment by TechSpiritSS** [comment]
done

**Comment by TechSpiritSS** [comment]
> > Add your component to general readme.
> 
> Do this!

Sorry, I didn't get this

**Comment by siddhi-244** [comment]
> > > Add your component to general readme.
> > 
> > 
> > Do this!
> 
> Sorry, I didn't get this

Refer to other prs

**Comment by TechSpiritSS** [comment]
Now it's all good?

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
