### PR TITLE
changed hover effect on preview text

### PR DESCRIPTION
**Pull request by niladrix719**
## What is the change?
I have changed the hover effect for the preview text which is inside every component box

## Related issue?
closes: #314

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [ ] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

https://user-images.githubusercontent.com/91966855/216104750-7ba86dcc-bfe9-4796-9fc9-7b60ea85ac24.mp4

### CODE REVIEW

**Comment by siddhi-244** [comment]
> ## What is the change?
> I have changed the hover effect for the preview text which is inside every component box
> 
> ## Related issue?
> closes: #314
> 
> ## How was it tested?
> Remove this line and tell us how the code was tested.
> 
> ## Checklist:
> Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:
> 
> * [x]  Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
> * [x]  Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
> * [ ]  Have you made corresponding changes to the documentation?
> * [x]  Have you tested the code before submission?
> * [x]  Have you formatted your code ? (You can use any html,css beautifier)
> * [x]  My changes generates no new warnings.
> * [x]  I'm Diversion2k23 contributor.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> 
> ## GIF/video of the working of component you created:
> Add here the GIF you created.

Add a video of the working component.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Also if you check the deploy preview the component cards are no more visible

**Comment by siddhi-244** [comment]
> Also if you check the deploy preview the component cards are no more visible

..

**Comment by niladrix719** [comment]
> > Also if you check the deploy preview the component cards are no more visible
> 
> ..

i think we are having some miss understanding the code break is not for this PR..rather for #[pull312](https://github.com/siddhi-244/Embellish/pull/312)...that's why I fixed it with my own RP #[pull322](https://github.com/siddhi-244/Embellish/pull/322) wichi is currently open and can fix it

**Comment by siddhi-244** [comment]
> > > Also if you check the deploy preview the component cards are no more visible
> > 
> > 
> > ..
> 
> i think we are having some miss understanding the code break is not for this PR..rather for #[pull312](https://github.com/siddhi-244/Embellish/pull/312) by someone...that's why I fixed the code break with my own RP #[pull322](https://github.com/siddhi-244/Embellish/pull/322) which is currently open and can fix it

It would be great if you can fix it in the same pr!

**Comment by niladrix719** [comment]
> > > > Also if you check the deploy preview the component cards are no more visible
> > > 
> > > 
> > > ..
> > 
> > 
> > i think we are having some miss understanding the code break is not for this PR..rather for #[pull312](https://github.com/siddhi-244/Embellish/pull/312) by someone...that's why I fixed the code break with my own RP #[pull322](https://github.com/siddhi-244/Embellish/pull/322) which is currently open and can fix it
> 
> It would be great if you can fix it in the same pr!

ok

**Comment by niladrix719** [comment]
> > > > Also if you check the deploy preview the component cards are no more visible
> > > 
> > > 
> > > ..
> > 
> > 
> > i think we are having some miss understanding the code break is not for this PR..rather for #[pull312](https://github.com/siddhi-244/Embellish/pull/312) by someone...that's why I fixed the code break with my own RP #[pull322](https://github.com/siddhi-244/Embellish/pull/322) which is currently open and can fix it
> 
> It would be great if you can fix it in the same pr!

done now the components should be visible

**Review by siddhi-244 — APPROVED** [review]
Well done !

**Pull request merged**
