### PR TITLE
Gradient_Background

### PR DESCRIPTION
**Pull request by SurajPratap10**
## What is the change?
I want to add a new component under the Background folder named Gradient_Background. 

## Related issue?
closes: #327 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md)while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] My changes generates no new warnings.
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

## GIF/video of the working of component you created:
Add here the GIF you created.
Gradient_Background — Mozilla Firefox 2023-02-02 09-30-59

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please remove the typing text animation

**Comment by SurajPratap10** [comment]
> Please remove the typing text animSorry,

> Please remove the typing text animation

Done

**Comment by SurajPratap10** [comment]
> Please remove the typing text animation

Done

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Remove the extra commits

**Pull request closed without merging**
